# Generated by Django 2.2.7 on 2020-03-13 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=7)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('affilation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('state', models.CharField(blank=True, max_length=300, null=True)),
                ('zip_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=7, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('research_topic', models.CharField(max_length=100)),
                ('research_location', models.CharField(max_length=100)),
                ('geographical_coverage', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('study_design', models.CharField(max_length=100)),
                ('study_population', models.PositiveIntegerField()),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('sampling_technique', models.CharField(max_length=100)),
                ('sampling_unit', models.CharField(max_length=100)),
                ('data_collection_tools', models.CharField(blank=True, max_length=100, null=True)),
                ('key_variables', models.CharField(blank=True, max_length=100, null=True)),
                ('key_indicators', models.TextField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('affilation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('sponsor', models.CharField(max_length=100)),
                ('data_codebook', models.FileField(blank=True, null=True, upload_to='')),
                ('questionaire', models.FileField(blank=True, null=True, upload_to='')),
                ('upload_data', models.FileField(blank=True, null=True, upload_to='')),
                ('permission', models.BooleanField(default=False)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('access', models.CharField(choices=[('open', 'Open'), ('restricted', 'Restricted')], default='open', max_length=20)),
                ('images', models.ImageField(upload_to='images')),
                ('file', models.FileField(upload_to='files')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Category')),
            ],
        ),
    ]
